on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

name: Lint Check
jobs:
  lint_test:
    name: 3.10 lint check
    runs-on: ubuntu-latest
    steps:
      - name: Set up python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Build package
        run: make package
      - name: Install package with dev deps
        run: |
          python -m pip install -e ".[dev]"
      - name: Run lint test
        run: make lint
